// Generated by CoffeeScript 1.6.3
(function() {
  var TaskCtrl, TasksCtrl, app_node, template;

  TasksCtrl = casua.defineController(function(scope) {
    scope.set('new_task_name', 'new');
    return {
      addNewTask: function() {
        scope.get('tasks').push({
          'name': scope.get('new_task_name')
        });
        scope.set('new_task_name', '');
        return false;
      }
    };
  });

  TaskCtrl = casua.defineController(function(scope) {
    return {
      taskClass: function() {
        if (scope.get('done')) {
          return 'is-done';
        } else {
          return '';
        }
      }
    };
  });

  app_node = new casua.Node(document.getElementById('todo-app'));

  template = {
    'ul.tasks-list': {
      '@child tasks': {
        '@controller': TaskCtrl,
        'li': {
          'input type="checkbox"': {
            '@attr checked': '@done'
          },
          '@attr class': '@taskClass()',
          'span': {
            '@html': 'Task {{name}}'
          }
        }
      }
    },
    'input type="text"': {
      '@val': '@new_task_name'
    },
    'br': '',
    'a href="#"': {
      '@on click': 'addNewTask',
      '@text': 'Add Task {{new_task_name}}'
    }
  };

  new TasksCtrl({
    'tasks': [
      {
        'name': 'one'
      }, {
        'name': 'two'
      }, {
        'name': 'three'
      }
    ]
  }).renderAt(app_node, template);

}).call(this);
